version: '3.9'

services:
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/project
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-service
      - postgres-service
    networks:
      - app
  postgres-service:
    image: postgres:15.2-alpine
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "db_test"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=en_US.utf8"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - '5432:5432'
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    networks:
      - app
  php-service:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php-container
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/project
      - ./docker/php/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    networks:
      - app

networks:
  app: